# Generated by Django 6.0.2 on 2026-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email_Id', models.CharField(max_length=50)),
                ('Mobile_no', models.IntegerField()),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
